	<footer class="footer hidden-print">
		<div class="container-fluid">
			<div class="row" style="margin:0;min-height:190px;max-height:190px;">
				<div class="col-xs-12 col-sm-12 col-md-4 text-justified footer-box">
					<strong>ΑΡΧΕΙΑΚΗ ΣΥΛΛΟΓΗ ΕΛΛΗΝΙΚΗΣ ΠΑΙΔΙΚΗΣ ΖΩΓΡΑΦΙΚΗΣ</strong></br>
							
								<a style="font-weight:normal;" href="mailto:paidiki.pinakothiki.elladas@gmail.com" class="social">Επικοινωνία</a></br>
								<a style="font-weight:normal;" href="aboutus.asp" class="social">Σχετικά με μας</a></br>
								<a style="font-weight:normal;" href="support.asp" class="social">Υποστηρίξτε μας</a></br>
					
				</div>
				
				<div class="col-xs-12 col-sm-12 col-md-5 text-center footer-box">
					<div class="footer-box-inner">
						<strong>ΟΡΟΙ ΧΡΗΣΗΣ &amp; ΠΟΛΙΤΙΚΗ ΑΠΟΡΡΥΤΟΥ</strong>
						<ul class="list-unstyled" style="margin:0;">
							<li class="link-list"><a class="social" href="terms.asp">Όροι Χρήσης</a></li>
							<li class="link-list"><a class="social" href="privacy.asp">Πολοτική Απορρήτου</a></li>
							<li class="link-list"><a class="social" href="sitemap.asp">Χάρτης Ιστοτόπου</a></li>
						</ul>
					</div>
					
					
				</div>
				
				<div class="col-xs-12 col-sm-12 col-md-3 text-center footer-box">
					<div style="position:relative;margin-top:20px;overflow:hidden">
					<p class="text-center">Ακολουθήστε μας στα Social Media</p>
					<a class="social" href="https://www.facebook.com/paidiki.pinakothiki.elladas" target="_blank" alt="Βρείτε μας στο Facebook" title="Βρείτε μας στο Facebook">
						<span class="fa-stack fa-lg">
							<i class="fa fa-facebook-official fa-stack-2x"></i>
						</span>
					</a>
					<a class="social" href="https://twitter.com/Pai_Pin_Ella" target="_blank" alt="Ακολουθήστε μας στο Twitter" title="Ακολουθήστε μας στο Twitter">
						<span class="fa-stack fa-lg">
							<i class="fa fa-twitter-square fa-stack-2x"></i>
						</span>
					</a>
					<a class="social" href="https://www.instagram.com/paidiki.pinakothiki.elladas/" target="_blank" alt="Ακολουθήστε μας στο Instagram" title="Ακολουθήστε μας στο Instagram">
						<span class="fa-stack fa-lg">
							<i class="fa fa-instagram fa-stack-2x"></i>
						</span>
					</a>
					<a class="social" href="https://plus.google.com/+%CE%A0%CE%B1%CE%B9%CE%B4%CE%B9%CE%BA%CE%AE%CE%A0%CE%B9%CE%BD%CE%B1%CE%BA%CE%BF%CE%B8%CE%AE%CE%BA%CE%B7%CE%95%CE%BB%CE%BB%CE%AC%CE%B4%CE%B1%CF%82/posts" target="_blank" alt="Ακολουθήστε μας στο Google+" title="Ακολουθήστε μας στο Google+">
						<span class="fa-stack fa-lg">
							<i class="fa fa-google-plus-square fa-stack-2x"></i>
						</span>
					</a>
					<a class="social" href="https://www.youtube.com/channel/UCxwFAShyOMMLnYAsBmb-L5A" target="_blank" alt="Ακολουθήστε το κανάλι μας στο YouTube" title="Ακολουθήστε το κανάλι μας στο YouTube">
						<span class="fa-stack fa-lg">
							<i class="fa fa-youtube-square fa-stack-2x"></i>
						</span>
					</a>
					</div>
				</div>
			</div>
			
			
			<div class="row" style="position:absolute;width:100%;bottom:0;min-height:50px;max-height:50px;margin-top:auto;">
				<div class="footer-strip">
					<div class="copyRight text-left">&copy; 2018, Παιδική Πινακοθήκη Ελλάδας. Όλα τα δικαιώματα δεσμευμένα.</div>
					<div class="createdBy text-right">Σχεδίαση &amp; Ανάπτυξη, Ιωάννης Πετρίδης</div>
				</div>
			</div>
		</div>
		
		
    </footer>