  		<nav style="min-height: 122px;" class="navbar navbar-default navbar-fixed-top marginBottom-0" role="navigation">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
					<span class="sr-only">ΜΕΝΟΥ ΠΛΟΗΓΗΣΗΣ</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand pull-left" style="padding-top:0px;" href="/">
					<img src="img/asepz_logo.png" height="122" alt="Αρχειακή Συλλογή Ελληνικής Παιδικής Ζωγραφικής - Αρχική Σελίδα" title="Αρχειακή Συλλογή Ελληνικής Παιδικής Ζωγραφικής - Αρχική Σελίδα">
				</a>
			</div>
            
			<div class="collapse navbar-collapse" id="navbar-collapse-1" style="padding-right:70px;">
				<ul class="nav navbar-nav" style="padding-left:44px;padding-top:44px;font-size:1.4em">
					<li class="top-level1">
						<a href="/">ΑΡΧΙΚΗ</a>
						
					</li>
					<li class="top-level2">
						<a href="collection.asp">Η ΣΥΛΛΟΓΗ</a>
					</li>
						
					<li class="top-level3">
						<a href="">ΕΚΠΑΙΔΕΥΤΙΚΟ ΥΛΙΚΟ </a>
						<ul class="dropdown-menu" style="font-size:14pt;">
							<li><a href="learntopaint.asp">Μαθαίνω να ζωγραφίζω</a></li>
							<li><a href="educational_units.asp">Εκπαιδευτικές Ενότητες</a></li>
							
						</ul>
					</li>
					
					<li class="top-level4" >
						<a href="">ΣΥΜΜΕΤΟΧΗ ΣΤΗΝ Α.Σ.Ε.Π.Σ. </a>
						<ul class="dropdown-menu" style="font-size:14pt;"> 
							<li><a href="actions.asp">Δράσεις &amp; Εκδηλώσεις</a></li>
							<li><a href="artwork_assesment.asp">Αξιολόγη Έργων</a></li>
							
						</ul>
					</li>
					
					<li class="top-level5">
						<a href="submit_artwork.asp" class="btn btn-primary" style="color:white;" role="button">Υποβολή Έργων</a>
					</li>
					
				</ul>
				
				
			</div>
			
		</nav>